version: '3.8'

services:
  server:
    build: .
    image: next_graphql_crm:v1 
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      CLIENT_URL: http://client:3000
      DATABASE_URL: mongodb://db:27017/CRMGraphQL 
      DB_MONGO: mongodb://db:27017/CRMGraphQL
    volumes:
      - .:/app 

  client:
    build:
      context: ./client
    image: next_graphql_crm_client:v1 
    ports:
      - "3000:3000"
    environment:
      API_URL: http://server:4000

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db 

volumes:
  mongo-data:
