import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import { ApolloWrapper } from "./config/apolloWrapper";
import Sidebar from './components/Sidebar'
import OrdersState from "./context/pedidos/ordersState";
import SidebarBurger from './components/SidebarBurger'


export const metadata = {
  title: 'CRM CLIENT ADMINISTRATION',
  description: 'Generated by create next app',
}
// eslint-disable-next-line @next/next/no-sync-scripts
export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <title>CRM CLIENT ADMINISTRATION</title>
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body className={inter.className}>
        <ApolloWrapper>
          <OrdersState>
            <div className="bg-gray-200 min-h-screen flex flex-col sm:flex-row">
              {/* <Sidebar className="w-full sm:w-1/4 lg:w-1/5" /> */}
              <SidebarBurger />
              <main className="bg-gray-200 min-h-screen p-5 w-full flex flex-col">
              <div className="w-full max-w-6xl mx-auto">
              {children}
                </div>
              </main>
            </div>
          </OrdersState>
        </ApolloWrapper>
      </body>
    </html>
  )
}
